import os
import pandas as pd
import numpy as np
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger("FeatureEngineering")

class FeatureEngineer:
    def __init__(self, data_path: str = "data/processed/baseline_features.parquet"):
        self.data_path = data_path
        self.df = None

    def load_data(self):
        """Loads baseline features generated by the preprocessing module."""
        if not os.path.exists(self.data_path):
            logger.error(f"Cannot find data at {self.data_path}. Please run preprocessing first.")
            return None
        self.df = pd.read_parquet(self.data_path)
        logger.info(f"Loaded baseline data with shape: {self.df.shape}")
        return self.df
        
    def _safe_divide(self, series1, series2, fill_value=0.0):
        """Helper for division by zero."""
        return series1.astype(float).div(series2.astype(float).replace(0, np.nan)).fillna(fill_value)

    def engineer_fair_value(self):
        """
        Calculates Fair Value Theoretical Price and the Premium/Discount divergence.
        Alpha core: theoretical_price = gold_price × usdinr × 0.0311
        premium_discount   = (etf_price - theoretical_price) / theoretical_price
        """
        if self.df is None or self.df.empty: return
        
        # Check if preprocessor already did conversion, or if core cols exist
        if "GC=F_INR_Gram_Close" in self.df.columns:
            theoretical_price = self.df["GC=F_INR_Gram_Close"]
            logger.info("Using pre-calculated GC=F_INR_Gram_Close for Fair Value.")
        elif "GC=F_Close" in self.df.columns and "USDINR_Close" in self.df.columns:
            logger.info("Calculating theoretical price dynamically from GC=F_Close & USDINR_Close.")
            theoretical_price = self.df["GC=F_Close"] * self.df["USDINR_Close"] * 0.0311
            self.df["GC=F_INR_Gram_Close"] = theoretical_price
        else:
            logger.warning("Components for Fair Value (GC=F_Close, USDINR_Close) missing. Skipping Fair Value features.")
            return

        if "GOLDBEES.NS_Close" in self.df.columns:
            logger.info("Computing Premium/Discount features...")
            self.df["Premium_Discount"] = self._safe_divide(
                self.df["GOLDBEES.NS_Close"] - theoretical_price, 
                theoretical_price
            )
            # Rolling Z-score of mispricing (capturing severe divergences)
            rolling_mean = self.df["Premium_Discount"].rolling(window=78, min_periods=20).mean()
            rolling_std = self.df["Premium_Discount"].rolling(window=78, min_periods=20).std()
            self.df["Premium_Discount_ZScore"] = self._safe_divide((self.df["Premium_Discount"] - rolling_mean), rolling_std)
        else:
            logger.warning("GOLDBEES.NS_Close is missing. Cannot calculate Premium/Discount.")

    def engineer_parkinson_volatility(self, window: int = 20):
        """
        Calculates Parkinson Volatility capturing intraday hidden risk within candles.
        Formula: sqrt( 1/(4 * ln2) * rolling_mean( ln(High/Low)^2 ) )
        """
        if self.df is None or self.df.empty: return
        
        req_cols = ["GOLDBEES.NS_High", "GOLDBEES.NS_Low"]
        if all(c in self.df.columns for c in req_cols):
            logger.info(f"Computing Parkinson Volatility (window={window})...")
            
            # Avoid division by zero by setting a floor for low
            safe_low = self.df["GOLDBEES.NS_Low"].replace(0, 1e-8)
            ln_hl_squared = np.log(self.df["GOLDBEES.NS_High"] / safe_low) ** 2
            
            # Standard vectorized rolling computation
            rolling_mean = ln_hl_squared.rolling(window=window, min_periods=window//2).mean()
            constant = 1.0 / (4.0 * np.log(2.0))
            
            self.df["Parkinson_Volatility"] = np.sqrt(constant * rolling_mean.fillna(0))
        else:
            logger.warning(f"Parkinson Vol missing required columns {req_cols}.")

    def engineer_relative_volume(self, window: int = 78):
        """
        Calculates Relative Volume (RV) & Detects Institutional Spikes.
        """
        if self.df is None or self.df.empty: return
        
        if "GOLDBEES.NS_Volume" in self.df.columns:
            logger.info(f"Computing Relative Volume (window={window})...")
            volume_sma = self.df["GOLDBEES.NS_Volume"].rolling(window=window, min_periods=window//2).mean()
            self.df["Relative_Volume"] = self._safe_divide(self.df["GOLDBEES.NS_Volume"], volume_sma)
            
            # Flag institutional-level volume spikes (e.g. > 2.5x normal avg limit)
            self.df["Volume_Spike_Flag"] = (self.df["Relative_Volume"] > 2.5).astype(int)
        else:
            logger.warning("Volume column missing. Cannot calculate Relative Volume features.")

    def build_lag_features_and_protect_lookahead(self):
        """
        To 100% physically guarantee NO look-ahead bias:
        1) Generate explicit multiple lags for short-term pattern memory (lag_1, lag_2, lag_3).
        2) Shift ALL generated model features by 1 period to align with forward-predicting rows.
        """
        if self.df is None or self.df.empty: return
        
        logger.info("Building multi-lag states and applying mandatory Look-Ahead Protection...")
        
        # 1. Multi-Lag Generation for core memory signals (on Returns, Volume, Volatility)
        core_lag_targets = []
        if "GOLDBEES.NS_Close" in self.df.columns:
            self.df["Returns_1_period"] = self.df["GOLDBEES.NS_Close"].pct_change(fill_method=None)
            core_lag_targets.append("Returns_1_period")
        
        if "Relative_Volume" in self.df.columns: core_lag_targets.append("Relative_Volume")
        if "Parkinson_Volatility" in self.df.columns: core_lag_targets.append("Parkinson_Volatility")

        for col in core_lag_targets:
            for lag in [1, 2, 3]:
                # Notice we do NOT over-shift here. 
                # We simply create columns 'col_lag_1', 'col_lag_2'.
                # The entire frame gets shifted at the end to guarantee safety.
                self.df[f"{col}_lag_{lag}"] = self.df[col].shift(lag)

        # 2. Strict Look-Ahead Protection block (Shift entire feature matrix +1)
        # Assuming the 'target' label hasn't been generated yet (which comes in Target Engineering).
        # We shift all features dynamically created in this module so they align temporally.
        feature_cols = [c for c in self.df.columns if c not in ["GOLDBEES.NS_Open", "GOLDBEES.NS_High", "GOLDBEES.NS_Low", "GOLDBEES.NS_Close", "GOLDBEES.NS_Volume"]]
        # We must shift OHLCV internally too if model consumes them as raw inputs directly
        logger.info("Shifting ALL analytical feature columns by +1 period to lock-out future data.")
        shifted_features = self.df.shift(1)
        
        # For our finalized feature-engineered set, we just keep the shifted frame entirely, 
        # so row T contains ONLY information known strictly before period T finished.
        self.df = shifted_features

    def run_pipeline(self, output_path: str = "data/processed/engineered_features.parquet"):
        """Executes full Alpha Generation Pipeline sequentially."""
        if self.df is None: self.load_data()
        
        self.engineer_fair_value()
        self.engineer_parkinson_volatility()
        self.engineer_relative_volume()
        self.build_lag_features_and_protect_lookahead()
        
        if self.df is not None and not self.df.empty:
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            self.df.to_parquet(output_path, engine='pyarrow', index=True)
            logger.info(f"Pipeline complete! Feature matrix securely saved -> {output_path}")
            logger.info(f"Final matrix shape: {self.df.shape}")

if __name__ == "__main__":
    fe = FeatureEngineer()
    fe.run_pipeline()
    
    if fe.df is not None:
        print("\n--- Final Engineered Feature Sample (Head) ---")
        display_cols = [c for c in fe.df.columns if any(x in c for x in ["Premium", "Parkinson", "Relative", "lag", "Returns"])]
        # Head with drops to show real computed rows instead of NaNs from shifting windows
        print(fe.df[display_cols].dropna().head(3))
